// ── Shared Types matching Prisma schema ──────────────────────

export type Role = 'ADMIN' | 'STAFF';
export type POStatus = 'DRAFT' | 'ORDERED' | 'IN_TRANSIT' | 'RECEIVED' | 'CANCELLED';
export type TransactionType = 'STOCK_IN' | 'STOCK_OUT' | 'ADJUSTMENT' | 'EXPIRED_REMOVAL';
export type AlertType = 'LOW_STOCK' | 'EXPIRY_WARNING' | 'EXPIRY_CRITICAL' | 'AUTO_PO_CREATED' | 'OUT_OF_STOCK';

export interface User {
  id: string;
  email: string;
  name: string;
  role: Role;
  createdAt: string;
}

export interface Supplier {
  id: string;
  name: string;
  email?: string;
  phone?: string;
  address?: string;
  leadTimeDays: number;
  createdAt: string;
}

export interface Product {
  id: string;
  sku: string;
  name: string;
  description?: string;
  category?: string;
  unit: string;
  costPrice: number;
  sellingPrice: number;
  reorderPoint: number;
  reorderQty: number;
  orderingCost: number;
  holdingCost: number;
  avgDailyDemand: number;
  supplier?: Supplier;
  supplierId?: string;
  totalQuantity?: number; // computed from inventory
  createdAt: string;
}

export interface Inventory {
  id: string;
  productId: string;
  product: Product;
  batchNo?: string;
  quantity: number;
  expiryDate?: string;
  location?: string;
}

export interface PurchaseOrder {
  id: string;
  poNumber: string;
  supplier: Supplier;
  status: POStatus;
  totalAmount: number;
  isAutoGenerated: boolean;
  expectedDelivery?: string;
  receivedAt?: string;
  notes?: string;
  items: PurchaseOrderItem[];
  createdAt: string;
}

export interface PurchaseOrderItem {
  id: string;
  product: Product;
  quantity: number;
  unitCost: number;
  totalCost: number;
}

export interface Alert {
  id: string;
  product: Product;
  type: AlertType;
  message: string;
  isRead: boolean;
  createdAt: string;
}

export interface DemandForecast {
  id: string;
  product: Product;
  forecastDate: string;
  predictedQty: number;
  actualQty?: number;
  algorithm: string;
}

// API response wrapper
export interface ApiResponse<T> {
  success: boolean;
  message: string;
  data: T;
}
