import { prisma } from '../utils/prisma';

/**
 * EOQ (Economic Order Quantity) Formula:
 * EOQ = √((2 × Demand × Ordering Cost) / Holding Cost)
 * 
 * This calculates the optimal order quantity that minimizes total inventory costs.
 */
export const calculateEOQ = (
  annualDemand: number,
  orderingCost: number,
  holdingCostPerUnit: number
): number => {
  if (annualDemand <= 0 || orderingCost <= 0 || holdingCostPerUnit <= 0) {
    return 0;
  }

  const eoq = Math.sqrt((2 * annualDemand * orderingCost) / holdingCostPerUnit);
  return Math.ceil(eoq); // Round up to whole units
};

/**
 * Reorder Point Formula:
 * Reorder Point = Daily Demand × Lead Time (in days)
 * 
 * This determines when to trigger a new order.
 */
export const calculateReorderPoint = (
  dailyDemand: number,
  leadTimeDays: number
): number => {
  return Math.ceil(dailyDemand * leadTimeDays);
};

/**
 * Check all products and create purchase orders for those below reorder point
 */
export const checkAndCreatePurchaseOrders = async () => {
  console.log('[REORDER SERVICE] Starting reorder check...');

  try {
    // Get all products with their inventory and supplier info
    const products = await prisma.product.findMany({
      include: {
        supplier: true,
        inventory: {
          select: { quantity: true },
        },
      },
    });

    let ordersCreated = 0;
    let skippedCount = 0;

    for (const product of products) {
      // Calculate current stock
      const currentStock = product.inventory.reduce((sum, inv) => sum + inv.quantity, 0);

      // Check if below reorder point
      if (currentStock >= product.reorderPoint) {
        continue; // Stock is healthy
      }

      // Skip if no supplier linked
      if (!product.supplierId || !product.supplier) {
        console.log(`⚠️  ${product.name} (${product.sku}) is low but has no supplier`);
        skippedCount++;
        continue;
      }

      // Calculate EOQ for optimal order quantity
      const annualDemand = product.avgDailyDemand * 365;
      const eoq = calculateEOQ(annualDemand, product.orderingCost, product.holdingCost);

      // Use EOQ if available, otherwise use default reorderQty
      const orderQuantity = eoq > 0 ? eoq : product.reorderQty;

      // Calculate expected delivery date based on supplier lead time
      const expectedDelivery = new Date();
      expectedDelivery.setDate(expectedDelivery.getDate() + product.supplier.leadTimeDays);

      // Check if there's already a pending order for this product
      const existingPO = await prisma.purchaseOrder.findFirst({
        where: {
          supplierId: product.supplierId,
          status: { in: ['DRAFT', 'ORDERED', 'IN_TRANSIT'] },
          items: {
            some: { productId: product.id },
          },
        },
      });

      if (existingPO) {
        console.log(`ℹ️  ${product.name} already has pending PO: ${existingPO.poNumber}`);
        continue;
      }

      // Create auto-generated purchase order
      const totalCost = orderQuantity * product.costPrice;

      const purchaseOrder = await prisma.purchaseOrder.create({
        data: {
          supplierId: product.supplierId,
          status: 'DRAFT',
          totalAmount: totalCost,
          isAutoGenerated: true,
          expectedDelivery,
          notes: `Auto-generated order using EOQ calculation (${eoq} units). Current stock: ${currentStock}, Reorder point: ${product.reorderPoint}`,
          items: {
            create: {
              productId: product.id,
              quantity: orderQuantity,
              unitCost: product.costPrice,
              totalCost,
            },
          },
        },
        include: {
          supplier: true,
          items: { include: { product: true } },
        },
      });

      // Create alert notification
      await prisma.alert.create({
        data: {
          productId: product.id,
          type: 'AUTO_PO_CREATED',
          message: `Auto-reorder triggered: PO #${purchaseOrder.poNumber} created for ${orderQuantity} units (EOQ-based). Expected delivery: ${expectedDelivery.toLocaleDateString()}`,
        },
      });

      console.log(`✅ Created auto-PO for ${product.name}: ${orderQuantity} units (EOQ: ${eoq})`);
      ordersCreated++;
    }

    console.log(`[REORDER SERVICE] Complete: ${ordersCreated} orders created, ${skippedCount} skipped (no supplier)`);

    return { ordersCreated, skippedCount };
  } catch (error) {
    console.error('[REORDER SERVICE] Error:', error);
    throw error;
  }
};

/**
 * Update average daily demand for a product based on recent sales
 * This should be called after each sale or periodically
 */
export const updateAverageDailyDemand = async (
  productId: string,
  lookbackDays: number = 30
): Promise<number> => {
  const startDate = new Date();
  startDate.setDate(startDate.getDate() - lookbackDays);

  const sales = await prisma.salesHistory.findMany({
    where: {
      productId,
      date: { gte: startDate },
    },
  });

  if (sales.length === 0) {
    return 0;
  }

  const totalQuantity = sales.reduce((sum, sale) => sum + sale.quantity, 0);
  const avgDailyDemand = totalQuantity / lookbackDays;

  // Update product
  await prisma.product.update({
    where: { id: productId },
    data: { avgDailyDemand },
  });

  return avgDailyDemand;
};