'use client';

import { useEffect, useState } from 'react';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { api } from '@/lib/api';
import { PurchaseOrder } from '@/lib/types';
import { Plus, Package, CheckCircle2, ArrowRight } from 'lucide-react';
import Link from 'next/link';

export default function OrdersPage() {
  const [orders, setOrders] = useState<PurchaseOrder[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<string>('all');

  const fetchOrders = async () => {
    try {
      const url = filter === 'all' ? '/purchase-orders' : `/purchase-orders?status=${filter}`;
      const res = await api.get(url);
      setOrders(res.data.data);
    } catch (err) {
      console.error('Failed to fetch orders:', err);
    } finally {
      setLoading(false);
    }
  };

  const updateStatus = async (id: string, newStatus: string) => {
    try {
      await api.patch(`/purchase-orders/${id}/status`, { status: newStatus });
      fetchOrders();
    } catch (err: any) {
      alert(err.response?.data?.message || 'Failed to update status');
    }
  };

  const receiveOrder = async (id: string) => {
    if (!confirm('Mark this order as received and add stock?')) return;

    try {
      await api.post(`/purchase-orders/${id}/receive`, {
        batchPrefix: 'PO',
        location: 'Warehouse A',
      });
      fetchOrders();
      alert('Order received and stock updated!');
    } catch (err: any) {
      alert(err.response?.data?.message || 'Failed to receive order');
    }
  };

  useEffect(() => {
    fetchOrders();
  }, [filter, fetchOrders]);

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'DRAFT':
        return 'gray';
      case 'ORDERED':
        return 'blue';
      case 'IN_TRANSIT':
        return 'yellow';
      case 'RECEIVED':
        return 'green';
      case 'CANCELLED':
        return 'red';
      default:
        return 'gray';
    }
  };

  if (loading) return <div className="text-center py-20">Loading orders...</div>;

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-slate-800">Purchase Orders</h1>
          <p className="text-slate-500 mt-1">{orders.length} orders</p>
        </div>
        <Link href="/orders/new">
          <Button>
            <Plus className="w-4 h-4" />
            New Purchase Order
          </Button>
        </Link>
      </div>

      <div className="flex gap-2">
        {['all', 'DRAFT', 'ORDERED', 'IN_TRANSIT', 'RECEIVED'].map((status) => (
          <Button
            key={status}
            size="sm"
            variant={filter === status ? 'primary' : 'secondary'}
            onClick={() => setFilter(status)}
          >
            {status === 'all' ? 'All' : status.replace(/_/g, ' ')}
          </Button>
        ))}
      </div>

      <div className="space-y-4">
        {orders.map((order) => (
          <Card key={order.id}>
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <div className="flex items-center gap-3 mb-2">
                  <h3 className="font-semibold text-lg text-slate-800">PO #{order.poNumber.slice(-8)}</h3>
                  <Badge variant={getStatusColor(order.status)}>{order.status.replace(/_/g, ' ')}</Badge>
                  {order.isAutoGenerated && <Badge variant="blue">Auto-generated</Badge>}
                </div>

                <div className="grid grid-cols-3 gap-4 text-sm mb-4">
                  <div>
                    <p className="text-slate-500">Supplier</p>
                    <p className="font-medium text-slate-800">{order.supplier.name}</p>
                  </div>
                  <div>
                    <p className="text-slate-500">Total Amount</p>
                    <p className="font-medium text-slate-800">${order.totalAmount.toFixed(2)}</p>
                  </div>
                  <div>
                    <p className="text-slate-500">Items</p>
                    <p className="font-medium text-slate-800">{order.items.length} products</p>
                  </div>
                </div>

                <div className="space-y-1 mb-3">
                  {order.items.map((item) => (
                    <div key={item.id} className="text-sm text-slate-600 flex items-center gap-2">
                      <Package className="w-4 h-4" />
                      {item.product.name} — {item.quantity} {item.product.unit} @ ${item.unitCost}
                    </div>
                  ))}
                </div>

                {order.notes && (
                  <div className="text-xs text-slate-500 bg-slate-50 p-2 rounded">
                    <strong>Notes:</strong> {order.notes}
                  </div>
                )}

                {order.expectedDelivery && (
                  <p className="text-xs text-slate-500 mt-3">
                    Expected: {new Date(order.expectedDelivery).toLocaleDateString()}
                  </p>
                )}
              </div>

              <div className="flex flex-col gap-2 ml-4">
                {/* Status progression buttons */}
                {order.status === 'DRAFT' && (
                  <Button size="sm" onClick={() => updateStatus(order.id, 'ORDERED')}>
                    <ArrowRight className="w-4 h-4" />
                    Mark as Ordered
                  </Button>
                )}
                
                {order.status === 'ORDERED' && (
                  <>
                    <Button size="sm" onClick={() => updateStatus(order.id, 'IN_TRANSIT')}>
                      <ArrowRight className="w-4 h-4" />
                      In Transit
                    </Button>
                    <Button size="sm" variant="secondary" onClick={() => receiveOrder(order.id)}>
                      <CheckCircle2 className="w-4 h-4" />
                      Receive Now
                    </Button>
                  </>
                )}
                
                {order.status === 'IN_TRANSIT' && (
                  <Button size="sm" onClick={() => receiveOrder(order.id)}>
                    <CheckCircle2 className="w-4 h-4" />
                    Receive Order
                  </Button>
                )}

                {order.status === 'RECEIVED' && (
                  <Badge variant="green">✓ Completed</Badge>
                )}
              </div>
            </div>
          </Card>
        ))}

        {orders.length === 0 && (
          <Card>
            <div className="text-center py-12 text-slate-500">
              No purchase orders yet. Create your first order to get started.
            </div>
          </Card>
        )}
      </div>
    </div>
  );
}